version: '3'
services:
    db:
        container_name: recipe-sharing-db
        image: postgres:14
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: password
    service:
        image: 'recipe-sharing:latest'
        build:
            context: .
        ports:
            - "8080:8080"
        container_name: recipe-sharing-service
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/azeti
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=password
